### ISSUE TITLE
This site has been reported as unsafe? Why?

### ISSUE THREAD

**Issue by JulyIghor** [elmerfdz/docker-traktarr#16]
![telegram-cloud-photo-size-2-5197552539111894525-y](https://user-images.githubusercontent.com/3390357/86668438-ebf64e80-bff2-11ea-895c-f3bf35c4468d.jpg)

**Comment by elmerfdz** [comment]
WTF! no idea mate, what browser is that?

**Comment by JulyIghor** [comment]
> WTF! no idea mate, what browser is that?

Microsoft Edge, latest update

**Comment by JulyIghor** [comment]
It was Microsoft Edge for iOS

**Comment by elmerfdz** [comment]
I tried it on Edge mobile (iOS) and desktop, I'm not getting that warning. Are you still having that issue?

**Comment by JulyIghor** [comment]
No longer reproduced
